### ISSUE TITLE
README message wrong

### ISSUE THREAD

**Issue by Preserver6166** [Debonex/m-league-data-fetcher#2]
game end points in L001_S010_0080_02A.json are wrong
A0: 26.4 -> 76.4 (这里应该是D0，不是A0)
B0: -42.8 -> -72.8

**Comment by Debonex** [comment]
感谢指正。

**Comment by Debonex** [comment]
现在添加了修复数据的脚本，所以README中的信息就去掉了

**Comment by Preserver6166** [comment]
赞👍🏻
